export const categories = [
  "Appetizers",
  "Breakfast",
  "Brunch",
  "Lunch",
  "Dinner",
  "Soups",
  "Salads",
  "Desserts",
  "Smoothies",
  "Snacks",
  "Pasta",
  "Pizza",
  "Burgers",
  "Sandwiches",
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Asian",
  "Italian",
  "Mexican",
  "Indian",
  "Mediterranean",
  "Middle Eastern",
  "American",
  "European",
  "African",
  "Latin American",
  "Sweets",
  "Cakes",
  "Cookies",
  "Pies",
  "Cupcakes",
  "Ice Cream",
  "Chocolate",
];

export const footerLinks = [
  {
    title: "For Foodies",
    links: [
      "Explore Recipes",
      "Food Blog",
      "Cooking Tips",
      "Food Podcast",
      "Food Photography",
      "Refer a Friend",
      "Terms of Use",
    ],
  },
  {
    title: "Food Delivery",
    links: [
      "Order Food Online",
      "Meal Delivery",
      "Catering Services",
      "Food Trucks",
    ],
  },
  {
    title: "Restaurants",
    links: ["Find Restaurants", "Restaurant Reviews", "Menu Showcase"],
  },
  {
    title: "Food Brands",
    links: ["Advertise with us"],
  },
  {
    title: "Company",
    links: [
      "About Us",
      "Careers",
      "Contact Us",
      "Media Kit",
      "Testimonials",
      "API",
      "Privacy Policy",
      "Cookie Policy",
    ],
  },
  {
    title: "Foodie Community",
    links: ["Food Events", "Food Festivals", "Food Forums", "Food Meetups"],
  },
  {
    title: "Food Resources",
    links: [
      "Healthy Eating",
      "Food Sustainability",
      "Cooking Classes",
      "Food Industry Trends",
      "Food Education",
    ],
  },
];
